spring:
  datasource:
    password: test123
    url: jdbc:mysql://mysql-docker-container:3306/spring_app_db?allowPublicKeyRetrieval=true&useSSL=false
    username: app_user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
